name: RA Workflow CI

on: pull_request

jobs:
  Parse_Commit:
    runs-on: ubuntu-latest
    outputs:
      commits: ${{ steps.parse.outputs.commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse commits
        id: parse
        run: |
          echo "::set-output name=commits::$(git log --pretty=tformat:"%s" --no-merges)"

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom
        uses: ./.github/actions/ra
        with:
          token: ${{ secrets.TOKEN }}
